### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by popcorn9499** [Tinob/Ishiiruka#75] opened 2017-04-15 00:07 UTC
It seemed to just kinda stop at [this point.](https://pastebin.com/cdJS4QzP) I'm not exactly sure why it didnt work. seemed to fail at the same place running both ubuntu 16.04 or 17.04 same thing occured. Anything else u need i will gladly provide.

Hope this helps. thanks

**Comment by Tinob** [comment] 2017-04-15 13:55
can you try now it should be fixed in the last version

**Comment by popcorn9499** [comment] 2017-04-15 15:42
failed again in a different spot this time [crash](https://pastebin.com/he4TWwUX)

**Comment by Tinob** [comment] 2017-04-15 16:44
please try again more fixes merged

**Comment by popcorn9499** [comment] 2017-04-16 04:49
it builds now i have a different issue. it wont load but im not sure if thats me running 17.04 or not. its complaining about a library 

> ./dolphin-emu: error while loading shared libraries: libsfml-network.so.2.3: cannot open shared object file: No such file or directory 

it does that when i try  to load dolphin. if i double click to execute it wont load at all either. i feel like im missing dependencies.

**Comment by KAMiKAZOW** [comment] 2017-04-16 10:50
Then install libsfml-network, duh.
Your dependency problem has nothing to do with this bug report. It builds just fine: https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/ishiiruka-dolphin-unstable/openSUSE_Tumbleweed/x86_64

Please close this bug report. Thanks for the fix, @Tinob

**Comment by popcorn9499** [comment] 2017-04-16 21:01
i have libsfml-network installed. its libsfml-network2.4 would i have to install 2.3 then?

**Comment by KAMiKAZOW** [comment] 2017-04-16 23:19
If you're interested in proper Ubuntu packages, I'm happy to accept contributions to https://build.opensuse.org/project/show/home:KAMiKAZOW:Emulators enabling that. I have next no clue about Debian/Ubuntu packaging, so I can't do it myself. You could adapt existing Dolphin packaging files. If done right, it would automatically take care of dependencies.

**Comment by popcorn9499** [comment] 2017-04-17 13:39
im trying to say that it used to work i know the build process works becuz it compiled everything fine. what im trying to say is that its not loading but ik it loads on a ubuntu lts system. so essentially im trying to ask is this something that i need to install the older package for or what?

**Comment by Tinob** [comment] 2017-04-17 15:26
the weir thing is why if you have 2.4 version it compiles against 2.3 did you recently upgraded your system?

**Comment by popcorn9499** [comment] 2017-04-17 20:40
i recently upgraded my system yes. so what exactly should i do?

**Comment by Tinob** [comment] 2017-04-17 21:11
the only idea that i could think is unistall the library and install it again to grant that no old versions remain in the system, can you post the output for cmake?

**Comment by popcorn9499** [comment] 2017-04-17 22:23
i built it on a different install on this system is i think what happened to be honest. but i didnt really think that it would complain about the version being newer. ill try rebuilding it on my current install and see what happens. would that be the probable cause? ill still output the cmake log for u. just pipe the cmake output to a text file should work. if not tell me

**Comment by Tinob** [comment] 2017-04-17 22:26
yes that will be perfect, yes building on a diferent install is the cause for shure

**Comment by popcorn9499** [comment] 2017-04-17 22:28
[cmake log](https://pastebin.com/6EktgSNG) That log should help you out. its the cmake log. i am running this on the current version of ubuntu that im running. before i think it was possible that the cause was cause the building was done on a older version of ubuntu. My desktop is running a older version of ubuntu and i built it there and tried to run it on my laptop. My desktop builds alot quicker is why i did that.

**Comment by popcorn9499** [comment] 2017-04-17 22:29
would there be a way that i could make this run on either version without building it on the right version of ubuntu? or do i need to build it on that system?

**Comment by Tinob** [comment] 2017-04-17 22:31
the only way is to create qa distributable package for your distro that will copy the dependencies with the app, without that the only way is compiling in your system

**Comment by popcorn9499** [comment] 2017-04-17 22:34
that would work with creating the portable version of ishiiruka?

**Comment by Tinob** [comment] 2017-04-17 22:34
yes

**Comment by popcorn9499** [comment] 2017-04-17 22:37
would u be able to point me in a direction to do this or no? just currious. thanks by the way

**Comment by Tinob** [comment] 2017-04-18 00:34
https://wiki.debian.org/HowToPackageForDebian is a good start point

**Comment by popcorn9499** [comment] 2017-04-19 21:21
Thanks im reading up on this and looking further. Im greatful that you have given me some direction to look.

**Closed** 2017-05-08 18:55 UTC
